# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-18 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('ACT1', 'Activity (Acrobatic)'), ('ACT2', 'Activity (Arcade)'), ('ACT3', 'Activity (Archery)'), ('ACT4', 'Activity (Bar)'), ('ACT5', 'Activity (Billiards)'), ('ACT6', 'Activity (Boat Rental)'), ('ACT7', 'Activity (Boat)'), ('ACT8', 'Activity (Bowling)'), ('ACT9', 'Activity (Bucket List)'), ('ACT10', 'Activity (Chill)'), ('ACT11', 'Activity (Experience)'), ('ACT12', 'Activity (Mini Golf)'), ('ACT13', 'Activity (Horseback Riding)'), ('ACT14', 'Activity (Ice Skating)'), ('ACT15', 'Activity (Karaoke)'), ('ACT16', 'Activity (Go Karting)'), ('ACT17', 'Activity (Movies)'), ('ACT18', 'Activity (Musuem)'), ('ACT19', 'Activity (Painting)'), ('ACT20', 'Activity (Park)'), ('ACT21', 'Activity (Play)'), ('ACT22', 'Activity (Zoo)'), ('AMU', 'Amusement Park'), ('DES', 'Dessert (D)'), ('DES_P', 'Dessert (P)'), ('DIN_D', 'Dinner (D)'), ('DIN_Deal', 'Dinner (Deal)'), ('DIN_M', 'Dinner (M)'), ('LUN', 'Lunch (D)'), ('STA', 'Stadium'), ('WEB', 'Website')], max_length=80)),
                ('address', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=5)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('notes', models.TextField(default=None, max_length=500, null=True)),
                ('website', models.URLField(default=None, max_length=120, null=True)),
                ('price', models.CharField(default=None, max_length=5, null=True)),
                ('parking', models.CharField(default=None, max_length=20, null=True)),
                ('maps', models.URLField(default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=40)),
                ('show', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
